# Generated by Django 5.1 on 2024-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_alerts',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
