# Generated by Django 5.1 on 2024-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anomaly_Detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recent_ship_issues',
            old_name='name',
            new_name='departed_from',
        ),
    ]
