# Generated by Django 5.1 on 2024-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anomaly_Detection', '0002_rename_name_recent_ship_issues_departed_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('mmsi', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
